clc;
close all;
clear;
% this program finds the Electric field at a point (1,2,3) due to two point
% charges 2 coulomb each at (0,0,1) and (0,0,-1) and an infinite linear charge density 5c/m lying
% along x axis.
% Debi Prasad Pattnaik, WWW.debipattnaik.com
Q1=2;%1st charge 
Q2=2;% 2nd charge
pL=5;%charge density
Eo=8.8419e-12;%Permitivity of free space 
  
P=[1 2 3];%coordinates of observation point 
A=[0 0 1];%coordinates of Q1 
B=[0 0 -1];%coordinates of Q2 
C=[2 0 0];%coordinates of the center of the line charge 
Number_of_L_Steps=100000;%the steps of L 

% Electric field due to point charges at points A, and B
R1=P-A; %the vector pointing from Q1 to the observation point 
R2=P-B; %the vector pointing from Q2 to the observation point 
R1Mag=norm(R1);%the magnitude of R1 
R2Mag=norm(R2);%the magnitude of R1 
E1=Q1/(4*pi*Eo*R1Mag^3)*R1;%the electric field generated by Q1 
E2=Q2/(4*pi*Eo*R2Mag^3)*R2;%the electric field generated by Q2
% simple as it is in MATLAB :)

% Electric field due to linear charge density
d=norm(P-C);%the distance from the observation point to the center of the line 
length=100*d;%the length of the line 
dL_V=length/Number_of_L_Steps*[1 0 0];%vector of a segment 
dL=norm(dL_V);%length of a segment 
EL=[0 0 0];%initialize the electric field generated by EL 
C_segment=C-( Number_of_L_Steps/2*dL_V-dL_V/2);%the center of the first segment 
for i=1: Number_of_L_Steps 
    R=P-C_segment;
 
    RMag=norm(R);%the magnitude of the vector R 
    EL=EL+dL*pL/(4*pi*Eo*RMag^3)*R;%get contibution from each segment  
    C_segment=C_segment+dL_V;%the center of the i-th segment 
end 
E=E1+E2+EL% the electric field at P 